function report = verify_stage89_initializations(summaryPath,outputPath)
% 只读取第8步真实原始记录并重建初猜；不构建OCP，不调用优化器。
% 调用前须将 matlab/numerical_scenarios 加入 MATLAB 路径。
cfg=numerical_cases_config();
if nargin<1 || isempty(summaryPath)
    summaryPath=fullfile(cfg.paths.data,'revision_checks','initialization_summary.json');
end
if nargin<2 || isempty(outputPath)
    outputPath=fullfile(fileparts(mfilename('fullpath')),'step89_initialization_validation.json');
end
assert(isfile(summaryPath),'stage89:MissingInitializationSummary', ...
    'Missing real initialization summary: %s.',summaryPath);
summary=jsondecode(fileread(summaryPath));
assert(isfield(summary,'group') && strcmp(summary.group,'initialization') && ...
    isfield(summary,'rows') && numel(summary.rows)==10, ...
    'stage89:InvalidInitializationSummary','Expected ten scheduled real initialization rows.');
indexPath=fullfile(cfg.paths.data,'run_index.json');
assert(isfile(indexPath),'stage89:MissingRunIndex','Missing run index: %s.',indexPath);
index=jsondecode(fileread(indexPath));
types={'constant_control','seeded_random'};
for k=1:5
    id=sprintf('E%d',k);
    for j=1:numel(types)
        assert(sum(strcmp({summary.rows.case_id},id) & ...
            strcmp({summary.rows.initialization},types{j}))==1, ...
            'stage89:InvalidInitializationSummary','Expected exactly one %s row for %s.',types{j},id);
    end
end
stateTolerance=1e-12;
report=struct('schema_version',1,'status','failed','passed',false, ...
    'checked_utc',numerical_utc(),'optimizer_calls',0, ...
    'source_summary',summaryPath,'source_summary_sha256',numerical_sha256(summaryPath,'file'), ...
    'source_index',indexPath,'source_index_sha256',numerical_sha256(indexPath,'file'), ...
    'initialization_state_tolerance',stateTolerance, ...
    'control_comparison','exact reconstruction of prescribed constant or local RandStream input', ...
    'state_comparison','saved node/internal states versus revision_initial_guess reintegration of actual piecewise constant input', ...
    'note','初猜验证与优化后数值接受分开；初猜容量超出允许并如实保存。', ...
    'expected_record_count',10,'validated_record_count',0,'rows',[]);
for k=1:numel(summary.rows)
    source=summary.rows(k);
    out=emptyRow(source);
    try
        ix=find(strcmp({index.entries.run_id},source.run_id));
        assert(isscalar(ix),'stage89:MissingRawRecord','Expected one raw record for %s.',source.run_id);
        entry=index.entries(ix); rawPath=fullfile(cfg.paths.data,entry.raw_file);
        assert(isfile(rawPath),'stage89:MissingRawRecord','Missing immutable raw file: %s.',rawPath);
        out.raw_file=rawPath; out.raw_sha256=numerical_sha256(rawPath,'file');
        assert(strcmp(out.raw_sha256,entry.raw_sha256), ...
            'stage89:RawRecordModified','Immutable raw hash differs for %s.',source.run_id);
        loaded=load(rawPath,'run'); run=loaded.run;
        assert(strcmp(run.run_id,source.run_id) && strcmp(run.case_id,source.case_id) && ...
            strcmp(run.solve_fingerprint,source.solve_fingerprint) && ...
            strcmp(entry.solve_fingerprint,source.solve_fingerprint), ...
            'stage89:SourceMismatch','Summary/index/raw identity differs for %s.',source.run_id);
        assert(strcmp(run.source_status,'verified_record') && ...
            strcmp(run.solve_fingerprint,numerical_sha256(run.solve_fingerprint_payload)), ...
            'stage89:SourceMismatch','Raw provenance fingerprint is invalid for %s.',source.run_id);
        assert(isequaln(run.initialization,run.solve_fingerprint_payload.initialization) && ...
            isequaln(run.initial_guess,run.solve_fingerprint_payload.initial_guess) && ...
            isequaln(run.actual_grid,run.solve_fingerprint_payload.actual_grid), ...
            'stage89:SourceMismatch','Saved initial arrays/grid differ from the fingerprinted actual request.');
        caseIndex=find(strcmp({cfg.cases.id},run.case_id));
        assert(isscalar(caseIndex),'stage89:UnexpectedCase','Unexpected case %s.',run.case_id);
        expectedOptions=cfg.solve; expectedOptions.N=cfg.cases(caseIndex).main_N;
        expectedOptions.initialization=source.initialization;
        assert(isequaln(run.solver_settings,expectedOptions) && ...
            isequal(run.parameters,cfg.parameters) && ...
            isequal(run.x0(:),cfg.cases(caseIndex).x0(:)) && ...
            strcmp(run.initialization.type,source.initialization), ...
            'stage89:ChangedProtocol','Saved initial request differs from the prescribed %s setup.',run.case_id);
        out.solve_success=logical(run.success); out.return_status=run.return_status;
        out.T=run.solver_settings.T; out.N=run.solver_settings.N;
        grid=run.actual_grid; tc=grid.t_control(:);
        saved=run.initial_guess; initial=run.initialization;
        assert(isequal(saved.t_control(:),tc) && ...
            isequal(saved.t_state(:),grid.t_state(:)) && ...
            isequal(saved.t_integrator(:),grid.t_integrator(:)), ...
            'stage89:InitialGridMismatch','Saved initial state/control times differ from the actual grid.');
        if strcmp(source.initialization,'constant_control')
            assert(isequal(initial.control,0.7),'stage89:ConstantGuessMismatch', ...
                'The prescribed constant input is 0.7.');
            qExpected=0.7*ones(size(tc));
            out.constant_control=initial.control;
            out.seed_definition_pass=isempty(initial.seed);
            out.knot_definition_pass=isempty(initial.knot_times) && isempty(initial.knot_values);
        else
            numericCase=str2double(run.case_id(2:end)); expectedSeed=20261008+numericCase;
            out.seed=initial.seed;
            out.seed_definition_pass=isequal(initial.seed,expectedSeed) && ...
                strcmp(initial.generator,'mt19937ar') && strcmp(initial.interpolation,'linear');
            knots=unique([0:2:min(20,out.T) out.T])';
            stream=RandStream('mt19937ar','Seed',expectedSeed);
            values=0.15+0.70*rand(stream,numel(knots),1);
            out.knot_times=initial.knot_times; out.knot_values=initial.knot_values;
            out.knot_value_max_abs_difference=max(abs(values-initial.knot_values(:)));
            out.knot_definition_pass=isequal(initial.knot_times(:),knots) && ...
                isequal(initial.knot_values(:),values) && isequal(initial.value_bounds,[0.15 0.85]);
            qExpected=interp1(knots,values,tc,'linear');
        end
        out.saved_control_min=min(saved.control(:)); out.saved_control_max=max(saved.control(:));
        out.control_max_abs_difference=maxDifference(saved.control,qExpected);
        out.initialization_control_max_abs_difference=maxDifference(initial.actual_control_guess,qExpected);
        out.control_exact_match=isequal(saved.control(:),qExpected) && ...
            isequal(initial.actual_control_guess(:),qExpected);
        before=rng;
        [reconstructedInitial,reconstructed]=revision_initial_guess(run.parameters,run.x0,out.T,grid,initial);
        out.global_rng_unchanged=isequaln(before,rng);
        out.reconstructed_control_exact_match=isequal(reconstructed.control(:),qExpected) && ...
            isequal(reconstructedInitial.actual_control_guess(:),qExpected);
        out.node_state_max_abs_difference=maxDifference(saved.node_states,reconstructed.node_states);
        out.integrator_state_max_abs_difference=maxDifference(saved.integrator_states,reconstructed.integrator_states);
        out.states_alias_max_abs_difference=maxDifference(saved.states,saved.node_states);
        out.saved_initial_capacity_excess=saved.capacity_excess;
        out.reconstructed_initial_capacity_excess=reconstructed.capacity_excess;
        out.initial_capacity_excess_difference=abs(saved.capacity_excess-reconstructed.capacity_excess);
        out.saved_integrator_sample_capacity_excess=saved.integrator_sample_capacity_excess;
        out.saved_ode_sample_capacity_excess=saved.ode_sample_capacity_excess;
        out.reconstructed_integrator_sample_capacity_excess=reconstructed.integrator_sample_capacity_excess;
        out.reconstructed_ode_sample_capacity_excess=reconstructed.ode_sample_capacity_excess;
        out.capacity_metric_max_abs_difference=max(abs([ ...
            saved.capacity_excess-reconstructed.capacity_excess, ...
            saved.integrator_sample_capacity_excess-reconstructed.integrator_sample_capacity_excess, ...
            saved.ode_sample_capacity_excess-reconstructed.ode_sample_capacity_excess]));
        out.passed=out.seed_definition_pass && out.knot_definition_pass && ...
            out.control_exact_match && out.reconstructed_control_exact_match && ...
            out.global_rng_unchanged && out.node_state_max_abs_difference<=stateTolerance && ...
            out.integrator_state_max_abs_difference<=stateTolerance && ...
            out.states_alias_max_abs_difference<=stateTolerance && ...
            out.capacity_metric_max_abs_difference<=stateTolerance;
        out.status='passed';
        if ~out.passed, out.status='failed'; out.reasons={'saved initialization reconstruction mismatch'}; end
    catch exception
        out.status='failed'; out.passed=false;
        out.reasons={exception.message};
        out.failure=struct('identifier',exception.identifier,'message',exception.message,'stack',exception.stack);
    end
    if isempty(report.rows), report.rows=out; else, report.rows(end+1)=out; end
    report.validated_record_count=numel(report.rows);
    numerical_write_json(outputPath,report);
end
report.passed=report.validated_record_count==10 && all([report.rows.passed]);
report.status='completed'; if ~report.passed, report.status='failed'; end
report.finished_utc=numerical_utc();
numerical_write_json(outputPath,report);
fprintf('STAGE89_INITIALIZATION_VALIDATION status=%s records=%d passed=%d optimizer_calls=0\n', ...
    report.status,report.validated_record_count,sum([report.rows.passed]));
end

function out=emptyRow(source)
out=struct('case_id',source.case_id,'configuration_id',source.configuration_id, ...
    'initialization',source.initialization,'run_id',source.run_id, ...
    'solve_fingerprint',source.solve_fingerprint,'raw_file','','raw_sha256','', ...
    'status','failed','passed',false,'solve_success',false,'return_status','not_available', ...
    'T',NaN,'N',NaN,'constant_control',[],'seed',[],'knot_times',[],'knot_values',[], ...
    'seed_definition_pass',false,'knot_definition_pass',false,'knot_value_max_abs_difference',NaN, ...
    'saved_control_min',NaN,'saved_control_max',NaN,'control_max_abs_difference',NaN, ...
    'initialization_control_max_abs_difference',NaN,'control_exact_match',false, ...
    'reconstructed_control_exact_match',false,'global_rng_unchanged',false, ...
    'node_state_max_abs_difference',NaN,'integrator_state_max_abs_difference',NaN, ...
    'states_alias_max_abs_difference',NaN,'saved_initial_capacity_excess',NaN, ...
    'reconstructed_initial_capacity_excess',NaN,'initial_capacity_excess_difference',NaN, ...
    'saved_integrator_sample_capacity_excess',NaN,'saved_ode_sample_capacity_excess',NaN, ...
    'reconstructed_integrator_sample_capacity_excess',NaN,'reconstructed_ode_sample_capacity_excess',NaN, ...
    'capacity_metric_max_abs_difference',NaN,'reasons',{{}},'failure',[]);
end

function difference=maxDifference(first,second)
assert(isequal(size(first),size(second)) && all(isfinite(first),'all') && all(isfinite(second),'all'), ...
    'stage89:InitialArrayMismatch','Saved and rebuilt initial arrays differ in dimensions or contain nonfinite values.');
difference=max(abs(first-second),[],'all');
end
