function run = solve_openocl_case(par,x0,opts,guess,prepared)
% 原直接配点问题；复用缓存检查阶段构建的实际问题和初猜。
if nargin<5, prepared=prepare_openocl_case(par,x0,opts,guess); end
[solution,times,info]=prepared.problem.solve(prepared.ig);
run=struct('parameters',par,'x0',x0(:),'solver_settings',prepared.solver_settings, ...
    'actual_solver_settings',prepared.actual_solver_settings,'actual_grid',prepared.actual_grid, ...
    'initialization',prepared.initialization,'initial_guess',prepared.initial_guess, ...
    't_state',reshape(times.states.value,[],1),'s_state',reshape(solution.states.S.value,[],1), ...
    'i_state',reshape(solution.states.I.value,[],1),'t_control',reshape(times.controls.value,[],1), ...
    'q_control',reshape(solution.controls.q.value,[],1),'success',logical(info.success), ...
    'return_status',info.ipopt_stats.return_status,'solver_info',info);
run.dt_control=diff([run.t_control;run.t_state(end)]);
assert(numel(run.q_control)==numel(run.dt_control) && all(run.dt_control>0));
run.J_openocl=par.p*par.c*sum(run.q_control.*run.dt_control);
assert(isequal(run.t_state,prepared.actual_grid.t_state) && ...
    isequal(run.t_control,prepared.actual_grid.t_control),'The returned grid differs from the fingerprinted grid.');
% 来源由execute_numerical_run在不可覆盖原始文件中记录。
end
